### PR TITLE
Yask update

### PR DESCRIPTION
**Pull request by chuckyount**

### CODE REVIEW

**Review by FabioLuporini — APPROVED** [review]
Thank you! Waiting for [CI to give the green light in Devito](https://github.com/opesci/devito/pull/763) and then I'll merge this.

**Comment by FabioLuporini** [comment]
@chuckyount CI seems to have found some errors:

https://travis-ci.org/opesci/devito/jobs/512506644

**Comment by FabioLuporini** [comment]
and here too: https://travis-ci.org/opesci/devito/jobs/512506630

(same errors)

**Comment by chuckyount** [comment]
I didn't think I was getting this error in my environment earlier, but now I can repro. I'll take a look.

**Comment by chuckyount** [comment]
I'm getting the same error with the _old_ version of YASK (2.18.00). So, it seems it's been there for a while.

**Comment by FabioLuporini** [comment]
Ok, the patch fixing the errors we were seeing has landed. Trying again with CI...

**Comment by FabioLuporini** [comment]
OK, devito's CI is green with this branch, so I'm landing it. THanks a lot

**Pull request merged**
