### PR TITLE
Yask updates

### PR DESCRIPTION
**Pull request by chuckyount**
Of most interest to Devito is a fix that allows running after building with debug knob `trace=1`.
There are math functions now in the DSL like sin(), sqrt(), etc., but these aren't yet available in the Python interface. Let me know if this might be useful in Devito.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
Nice, thanks.

> There are math functions now in the DSL like sin(), sqrt(), etc., but these aren't yet available in the Python interface. Let me know if this might be useful in Devito.

We do support them via SymPy and sure, ultimately we want to be able to run them through YASK. Do you simply turn them into calls to standard library functions, or do you do anything smarter? sin/cos/... are known to badly affect SIMD vectorisation, so I'm curious to learn about what you've done. In devito we used to support polynomial approximation (taylor's, bhaskara's, ...) but we haven't used it in a while. 

Out of curiosity, in TTI there indeed is extensive use of sin/cos/..., but only over time-invariant data, so perhaps not a big deal. 

still out of curiosity, on the devito side of things, presumably we'll have to add a further handler somewhere here: https://github.com/opesci/devito/blob/master/devito/yask/transformer.py#L186 
and equip the code with the necessary tests. Of course I'll take care of that, probably as soon as we have a relevant use case

**Comment by chuckyount** [comment]
The Intel compiler + run-time lib has vectorized versions of most math fns, so those are used. For one implementation of TTI, we found that calling both sin() and cos() on a single constant is faster on SKX than loading pre-computed const sin() and cos() values. It is still faster to pre-compute the 2 values on KNL.

**Comment by FabioLuporini** [comment]
I'm opening a branch in devito pulling from this PR's branch, rather than from this fork's master, to check that all tests still pass. If yes, I'll land this. Thanks again !

**Comment by FabioLuporini** [comment]
Update: https://github.com/opesci/devito/pull/763

Let's see how CI behaves...

**Review by FabioLuporini — APPROVED** [review]

**Comment by FabioLuporini** [comment]
OK, all good, merging. Thanks a lot for this, @chuckyount .

**Pull request merged**
